spring.application.name=flickzz-desk
server.servlet.context-path=/flickzz-desk

spring.jpa.hibernate.ddl-auto=none
#spring.datasource.url=jdbc:postgresql://localhost/flickzz_desk_local  ---- to use postgres 17

# Local configuration starts
spring.datasource.url=jdbc:postgresql://localhost:5433/flickzz_desk_local
spring.datasource.username=postgres
spring.datasource.password=flickzz
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
application.baseUrl=http://localhost:4200
server.port=5000

# Local configuration ends

# Refresh token validity: 1 day (24 * 60 * 60 * 1000)
jwt.refresh.expiration=86400000
# Refresh token validity: 7 day(7 * 24 * 60 * 60 * 1000)
jwt.refresh.expiration.extended=604800000 
jwt.secret=mysuperlongsecretkeystringthatishardtoguessflickzzdesksecret
#Jwt access token expiry (15 * 60 * 60 * 1000)
jwt.expiration=54000000  



# Railway deployment configuration starts
#spring.datasource.url=jdbc:postgresql://acela.proxy.rlwy.net:44380/railway
#spring.datasource.username=postgres
#spring.datasource.password=NAuVLCRPCBIBIFlUSRGrMAWnFbCNLEaT
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.show-sql=true
#
#application.baseUrl=https://flickzz-desk-ui-production.up.railway.app
#server.port=${PORT:8080}
# Railway deployment configuration ends

# Local Mail configuration (replace values with your SMTP provider details)
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=sindhuela95@gmail.com
#spring.mail.password=pfggpkpilpeuveul
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true
#spring.mail.properties.mail.debug=true
#spring.mail.default-encoding=UTF-8
#spring.mail.from=noreply@flickzzdesk.com
#app.mail.from=noreply@flickzzdesk.com

# Resend Email API Configuration
resend.api.key=re_B7dVvYKR_GQpViJLfuX8gep42xpaNXxfs
app.mail.from=noreply@flickzz32.com

uid.prefix=UIDXI01
# Root logging level (Options: TRACE, DEBUG, INFO, WARN, ERROR)
logging.level.root=INFO
logging.level.com.flickzz.desk=DEBUG
default.password=FlickzzDesk@2026