-- FD_COUNTRY_MASTER TABLE
ALTER TABLE FD_COUNTRY_MASTER
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_COUNTRY_MASTER
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_COUNTRY_MASTER
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_STATE_MASTER TABLE
ALTER TABLE FD_STATE_MASTER
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_STATE_MASTER
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_STATE_MASTER
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_CITY_MASTER TABLE
ALTER TABLE FD_CITY_MASTER
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_CITY_MASTER
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_CITY_MASTER
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_LANGUAGE_MASTER TABLE
ALTER TABLE FD_LANGUAGE_MASTER
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_LANGUAGE_MASTER
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_LANGUAGE_MASTER
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_USER TABLE
ALTER TABLE FD_USER
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_USER
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_USER
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_COMPANY_MASTER TABLE
ALTER TABLE FD_COMPANY_MASTER
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_COMPANY_MASTER
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_COMPANY_MASTER
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_COMPANY_ROLES TABLE
ALTER TABLE FD_COMPANY_ROLES
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_COMPANY_ROLES
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_COMPANY_ROLES
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_AUTH TABLE
ALTER TABLE FD_AUTH
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_AUTH
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_AUTH
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_LOGIN_MASTER TABLE
ALTER TABLE FD_LOGIN_MASTER
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_LOGIN_MASTER
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_LOGIN_MASTER
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_CALENDAR_TYPE TABLE
ALTER TABLE FD_CALENDAR_TYPE
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_CALENDAR_TYPE
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_CALENDAR_TYPE
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_CALENDAR_MASTER TABLE
ALTER TABLE FD_CALENDAR_MASTER
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_CALENDAR_MASTER
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_CALENDAR_MASTER
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_CALENDAR_HOLIDAY TABLE
ALTER TABLE FD_CALENDAR_HOLIDAY
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_CALENDAR_HOLIDAY
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_CALENDAR_HOLIDAY
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_CALENDAR_WORKDAYS TABLE
ALTER TABLE FD_CALENDAR_WORKDAYS
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_CALENDAR_WORKDAYS
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_CALENDAR_WORKDAYS
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_PLANT_MASTER TABLE
ALTER TABLE FD_PLANT_MASTER
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_PLANT_MASTER
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_PLANT_MASTER
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_SKILL_MASTER TABLE
ALTER TABLE FD_SKILL_MASTER
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_SKILL_MASTER
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_SKILL_MASTER
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_AGENT_MASTER TABLE
ALTER TABLE FD_AGENT_MASTER
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_AGENT_MASTER
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_AGENT_MASTER
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_AGENT_SKILLS_MAPPING TABLE
ALTER TABLE FD_AGENT_SKILLS_MAPPING
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_AGENT_SKILLS_MAPPING
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_AGENT_SKILLS_MAPPING
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_PRIORITY_MASTER TABLE
ALTER TABLE FD_PRIORITY_MASTER
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_PRIORITY_MASTER
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_PRIORITY_MASTER
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_BUSINESS_SERVICE TABLE
ALTER TABLE FD_BUSINESS_SERVICE
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_BUSINESS_SERVICE
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_BUSINESS_SERVICE
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_SERVICE_OFFERING TABLE
ALTER TABLE FD_SERVICE_OFFERING
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_SERVICE_OFFERING
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_SERVICE_OFFERING
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_REQUEST_CONFIG TABLE
ALTER TABLE FD_REQUEST_CONFIG
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_REQUEST_CONFIG
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_REQUEST_CONFIG
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_IMPACT_MASTER TABLE
ALTER TABLE FD_IMPACT_MASTER
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_IMPACT_MASTER
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_IMPACT_MASTER
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_TICKET TABLE
ALTER TABLE FD_TICKET
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_TICKET
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_TICKET
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_PROJECT TABLE
ALTER TABLE FD_PROJECT
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_PROJECT
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_PROJECT
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_PROGRESS_STATUS TABLE
ALTER TABLE FD_PROGRESS_STATUS
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_PROGRESS_STATUS
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_PROGRESS_STATUS
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_EPIC TABLE
ALTER TABLE FD_EPIC
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_EPIC
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_EPIC
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_USER_STORY TABLE
ALTER TABLE FD_USER_STORY
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_USER_STORY
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_USER_STORY
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_TASK TABLE
ALTER TABLE FD_TASK
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_TASK
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_TASK
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_SUB_TASK TABLE
ALTER TABLE FD_SUB_TASK
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_SUB_TASK
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_SUB_TASK
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_PROJECT_LEAD_ASSIGNMENT TABLE
ALTER TABLE FD_PROJECT_LEAD_ASSIGNMENT
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_PROJECT_LEAD_ASSIGNMENT
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_PROJECT_LEAD_ASSIGNMENT
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_WORK_ITEMS TABLE
ALTER TABLE FD_WORK_ITEMS
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_WORK_ITEMS
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_WORK_ITEMS
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_FIELD_TYPES TABLE
ALTER TABLE FD_FIELD_TYPES
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_FIELD_TYPES
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_FIELD_TYPES
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_TEMPLATE_DETAILS TABLE
ALTER TABLE FD_TEMPLATE_DETAILS
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_TEMPLATE_DETAILS
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_TEMPLATE_DETAILS
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_TEMPLATE_DETAIL_FIELD TABLE
ALTER TABLE FD_TEMPLATE_DETAIL_FIELD
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_TEMPLATE_DETAIL_FIELD
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_TEMPLATE_DETAIL_FIELD
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- FD_TEMPLATE_FIELD_OPTION TABLE
ALTER TABLE FD_TEMPLATE_FIELD_OPTION
    DROP COLUMN IF EXISTS CREATED_BY,
    DROP COLUMN IF EXISTS UPDATED_BY;
	
ALTER TABLE FD_TEMPLATE_FIELD_OPTION
    ADD COLUMN CREATED_BY BIGINT DEFAULT 3,
    ADD COLUMN UPDATED_BY BIGINT,
    ADD COLUMN IS_CREATOR_ADMIN BOOLEAN DEFAULT FALSE,
    ADD COLUMN IS_UPDATER_ADMIN BOOLEAN DEFAULT FALSE;
	
ALTER TABLE FD_TEMPLATE_FIELD_OPTION
    ALTER COLUMN CREATED_BY SET NOT NULL,
    ALTER COLUMN IS_CREATOR_ADMIN SET NOT NULL,
    ALTER COLUMN CREATED_BY DROP DEFAULT,
    ALTER COLUMN IS_CREATOR_ADMIN DROP DEFAULT;

-- 27/06/2026     
-- Rename table
ALTER TABLE FD_COMPANY_ROLES
RENAME TO FD_BUSINESS_PARTNER;

-- Add columns as nullable first
ALTER TABLE FD_BUSINESS_PARTNER
ADD COLUMN CALL_HORIZON BIGINT DEFAULT 0,
ADD COLUMN VALID_FROM TIMESTAMP,
ADD COLUMN VALID_TO TIMESTAMP,
ADD COLUMN REF_NO VARCHAR(100),
ADD COLUMN REF_DATE TIMESTAMP;

-- Populate existing records (adjust values as required)
UPDATE FD_BUSINESS_PARTNER
SET VALID_FROM = CURRENT_TIMESTAMP,
    VALID_TO = CURRENT_TIMESTAMP;

-- Make the columns NOT NULL
ALTER TABLE FD_BUSINESS_PARTNER
ALTER COLUMN VALID_FROM SET NOT NULL,
ALTER COLUMN VALID_TO SET NOT NULL;

UPDATE FD_BUSINESS_PARTNER
SET VALID_TO = VALID_FROM
             + ((floor(random() * 365) + 1) * INTERVAL '1 day');
             
UPDATE FD_BUSINESS_PARTNER
SET CALL_HORIZON = (VALID_TO::date - VALID_FROM::date) - 3;

UPDATE FD_BUSINESS_PARTNER
SET REF_NO = UPPER(SUBSTRING(md5(random()::text || clock_timestamp()::text) FROM 1 FOR 10));

ALTER TABLE FD_BUSINESS_PARTNER
RENAME CONSTRAINT FK_COMPANY_ROLE_COMPANY
TO FK_BUSINESS_PARTNER_COMPANY;

ALTER TABLE FD_BUSINESS_PARTNER
RENAME CONSTRAINT FK_COMPANY_ROLE_MAPPING_COMPANY
TO FK_BUSINESS_PARTNER_MAPPING_COMPANY;

ALTER TABLE FD_BUSINESS_PARTNER
RENAME CONSTRAINT UQ_COMPANY_ROLE_MAPPING
TO UQ_BUSINESS_PARTNER_MAPPING;

-- Rename the sequence
ALTER SEQUENCE COMPANY_ROLE_SEQ
RENAME TO BUSINESS_PARTNER_SEQ;

-- Update the default on ROLE_ID
ALTER TABLE FD_BUSINESS_PARTNER
ALTER COLUMN ROLE_ID
SET DEFAULT nextval('BUSINESS_PARTNER_SEQ');

SELECT setval(
    'BUSINESS_PARTNER_SEQ',
    COALESCE((SELECT MAX(ROLE_ID) FROM FD_BUSINESS_PARTNER), 0)
);

ALTER TABLE FD_BUSINESS_PARTNER
ALTER COLUMN CALL_HORIZON TYPE INT USING CALL_HORIZON::INT,
ALTER COLUMN CALL_HORIZON SET DEFAULT 0;