-- CREATE DATABASE FLICKZZ_DESK_LOCAL;

-- CREATE SEQUENCE FOR FD_COUNTRY_MASTER TABLE
CREATE SEQUENCE COUNTRY_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_COUNTRY_MASTER TABLE
CREATE TABLE FD_COUNTRY_MASTER (
    COUNTRY_ID BIGINT PRIMARY KEY DEFAULT nextval('COUNTRY_SEQ'),
    COUNTRY_NAME VARCHAR(100) NOT NULL UNIQUE,
    ISO_CODE VARCHAR(3) NOT NULL UNIQUE,
	PHONE_CODE VARCHAR(10) NOT NULL,
	CURRENCY_CODE VARCHAR(10), -- INR, USD 
	CURRENCY_NAME VARCHAR(50), 
	TIMEZONE VARCHAR(100),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- CREATE SEQUENCE FOR FD_STATE_MASTER TABLE
CREATE SEQUENCE STATE_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_STATE_MASTER TABLE
CREATE TABLE FD_STATE_MASTER (
    STATE_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('STATE_SEQ'),
    STATE_NAME VARCHAR(100) NOT NULL UNIQUE,
    STATE_CODE VARCHAR(10) UNIQUE,               -- OPTIONAL SHORT CODE (E.G., TN, CA)
    COUNTRY_ID BIGINT NOT NULL,                  -- FK TO FD_COUNTRY_MASTER
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_STATE_COUNTRY FOREIGN KEY (COUNTRY_ID)
        REFERENCES FD_COUNTRY_MASTER(COUNTRY_ID)
);

-- CREATE SEQUENCE FOR FD_CITY_MASTER TABLE
CREATE SEQUENCE CITY_SEQ
    START WITH 1
    INCREMENT BY 1;

-- UPDATE FD_CITY_MASTER TO LINK TO STATE INSTEAD OF JUST COUNTRY
CREATE TABLE FD_CITY_MASTER (
    CITY_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('CITY_SEQ'),
    CITY_NAME VARCHAR(100) NOT NULL,
    CITY_CODE VARCHAR(50) UNIQUE NOT NULL,
    STATE_ID BIGINT NOT NULL,                    -- FK TO FD_STATE_MASTER
    COUNTRY_ID BIGINT NOT NULL,                  -- REDUNDANT BUT USEFUL FOR REPORTING
    TIMEZONE VARCHAR(100),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CITY_STATE FOREIGN KEY (STATE_ID)
        REFERENCES FD_STATE_MASTER(STATE_ID),
    CONSTRAINT FK_CITY_COUNTRY FOREIGN KEY (COUNTRY_ID)
        REFERENCES FD_COUNTRY_MASTER(COUNTRY_ID)
);

-- CREATE SEQUENCE FOR FD_LANGUAGE_MASTER TABLE
CREATE SEQUENCE LANGUAGE_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_LANGUAGE_MASTER TABLE
CREATE TABLE FD_LANGUAGE_MASTER (
    LANGUAGE_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('LANGUAGE_SEQ'),
    LANGUAGE_NAME VARCHAR(100) NOT NULL UNIQUE,   -- FULL NAME (E.G., ENGLISH, HINDI)
    LANGUAGE_CODE VARCHAR(10) NOT NULL UNIQUE,    -- ISO CODE (E.G., EN, HI)
    IS_ACTIVE BOOLEAN DEFAULT TRUE,               -- STATUS FLAG
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- CREATE SEQUENCE FD_USER
CREATE SEQUENCE USER_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_USER TABLE
CREATE TABLE FD_USER (
    USER_ID BIGINT PRIMARY KEY DEFAULT nextval('USER_SEQ'),
    USER_NAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL UNIQUE,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    REGISTER_ID VARCHAR(50),
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    ROLE VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20) UNIQUE NOT NULL,
    COUNTRY_ID BIGINT,
    CITY_ID BIGINT,
    LANGUAGE_ID BIGINT,
    MFA_ENABLED BOOLEAN NOT NULL,
    SECRET VARCHAR(255),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50) DEFAULT 'SYSTEM',
    UPDATED_BY VARCHAR(50) DEFAULT 'SYSTEM',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT FK_USER_COUNTRY FOREIGN KEY (COUNTRY_ID)
        REFERENCES FD_COUNTRY_MASTER(COUNTRY_ID),
    CONSTRAINT FK_USER_CITY FOREIGN KEY (CITY_ID)
        REFERENCES FD_CITY_MASTER(CITY_ID),
    CONSTRAINT FK_USER_LANGUAGE FOREIGN KEY (LANGUAGE_ID)
        REFERENCES FD_LANGUAGE_MASTER(LANGUAGE_ID)
);

-- CREATE SEQUENCE FD_AUTH
CREATE SEQUENCE AUTH_SEQ
    START WITH 1
    INCREMENT BY 1;
    
-- CREATE FD_AUTH TABLE
CREATE TABLE FD_AUTH (
    AUTH_ID BIGINT PRIMARY KEY DEFAULT nextval('AUTH_SEQ'),
    TOKEN VARCHAR(255) NOT NULL UNIQUE,
    EXPIRES_AT TIMESTAMP NOT NULL,
    USER_ID BIGINT NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50) DEFAULT 'SYSTEM',
    UPDATED_BY VARCHAR(50) DEFAULT 'SYSTEM',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FD_USERS_REFRESH_TOKEN FOREIGN KEY (USER_ID)
        REFERENCES FD_USER(USER_ID)
);

-- CREATE SEQUENCE FD_LOGIN_MASTER
CREATE SEQUENCE LOGIN_SEQ 
	START WITH 1 
	INCREMENT BY 1;

-- CREATE FD_LOGIN_MASTER TABLE
CREATE TABLE FD_LOGIN_MASTER (
    LOGIN_ID BIGINT PRIMARY KEY DEFAULT nextval('LOGIN_SEQ'),
    USER_NAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL UNIQUE,
    ROLE VARCHAR(100) NOT NULL,
    LAST_LOGIN_DATETIME TIMESTAMP,
    USER_ID BIGINT NOT NULL UNIQUE,
    AUTH_ID BIGINT UNIQUE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50) DEFAULT 'SYSTEM',
    UPDATED_BY VARCHAR(50) DEFAULT 'SYSTEM',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_LOGIN_USER FOREIGN KEY (USER_ID)
        REFERENCES FD_USER(USER_ID),
    CONSTRAINT FK_LOGIN_AUTH FOREIGN KEY (AUTH_ID)
        REFERENCES FD_AUTH(AUTH_ID)
);

-- CREATE SEQUENCE FOR FD_CALENDAR_MASTER TABLE
CREATE SEQUENCE CALENDAR_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_CALENDAR_MASTER TABLE
CREATE TABLE FD_CALENDAR_MASTER (
    CALENDAR_ID BIGINT PRIMARY KEY DEFAULT nextval('CALENDAR_SEQ'),
    CALENDAR_CODE VARCHAR(20) NOT NULL UNIQUE,
    CALENDAR_TYPE VARCHAR(20) NOT NULL,
    VALID_FROM TIMESTAMP NOT NULL,   -- YYYY
    VALID_TO TIMESTAMP NOT NULL,     -- YYYY
    WORK_FROM VARCHAR(10),       -- HH:mm stored as TIMESTAMP
    WORK_TO VARCHAR(10),         -- HH:mm stored as TIMESTAMP
    TIMEZONE VARCHAR(50),
	IS_SUPPORT BOOLEAN DEFAULT FALSE,
	IS_REQUESTOR BOOLEAN DEFAULT FALSE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);

-- CREATE SEQUENCE FOR FD_SUBMENU TABLE
CREATE SEQUENCE CALENDAR_HOLIDAY_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_CALENDAR_HOLIDAY TABLE
CREATE TABLE FD_CALENDAR_HOLIDAY (
    HOLIDAY_ID BIGINT PRIMARY KEY DEFAULT nextval('CALENDAR_HOLIDAY_SEQ'),
    HOLIDAY_DATE TIMESTAMP NOT NULL,       -- DD.MM.YYYY format
    DESCRIPTION VARCHAR(255),
    CALENDAR_ID BIGINT NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT FD_CALENDAR_HOLIDAY FOREIGN KEY (CALENDAR_ID)
        REFERENCES FD_CALENDAR_MASTER(CALENDAR_ID)
);

-- CREATE SEQUENCE FOR FD_CALENDAR_WORKDAYS TABLE
CREATE SEQUENCE WORKDAY_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_CALENDAR_WORKDAYS TABLE
CREATE TABLE FD_CALENDAR_WORKDAYS (
    WORKDAY_ID BIGINT PRIMARY KEY DEFAULT nextval('WORKDAY_SEQ'),
    WORKDAY VARCHAR(20) NOT NULL,       -- e.g., "Monday", "Tuesday"
    CALENDAR_ID BIGINT NOT NULL,        -- FK to FD_CALENDAR_MASTER
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT FK_WORKDAY_CALENDAR FOREIGN KEY (CALENDAR_ID)
        REFERENCES FD_CALENDAR_MASTER(CALENDAR_ID)
);

-- CREATE SEQUENCE FOR FD_COMPANY_MASTER TABLE
CREATE SEQUENCE COMPANY_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_COMPANY_MASTER TABLE
CREATE TABLE FD_COMPANY_MASTER (
    COMPANY_ID BIGINT PRIMARY KEY DEFAULT nextval('COMPANY_SEQ'),
    COMPANY_NAME VARCHAR(255) NOT NULL UNIQUE,
    REGISTERED_NUMBER VARCHAR(100) NOT NULL,
    COUNTRY_ID BIGINT NOT NULL,
    ADDRESS VARCHAR(255),
    MAIL VARCHAR(100),
    IS_SERVICE_PROVIDER BOOLEAN DEFAULT FALSE,
    IS_REQUESTOR BOOLEAN DEFAULT FALSE,
    IS_BOTH BOOLEAN DEFAULT FALSE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,	
    CONSTRAINT FK_COMPANY_COUNTRY FOREIGN KEY (COUNTRY_ID)
        REFERENCES FD_COUNTRY_MASTER(COUNTRY_ID)
);

-- CREATE SEQUENCE FOR FD_PLANT_MASTER TABLE
CREATE SEQUENCE PLANT_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_PLANT_MASTER TABLE
CREATE TABLE FD_PLANT_MASTER (
    PLANT_ID BIGINT PRIMARY KEY DEFAULT nextval('PLANT_SEQ'),
    PLANT_NAME VARCHAR(255) NOT NULL UNIQUE,
    COUNTRY_ID BIGINT NOT NULL,
    CALENDAR_ID BIGINT NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PLANT_COUNTRY FOREIGN KEY (COUNTRY_ID)
        REFERENCES FD_COUNTRY_MASTER(COUNTRY_ID),
    CONSTRAINT FK_PLANT_CALENDAR FOREIGN KEY (CALENDAR_ID)
        REFERENCES FD_CALENDAR_MASTER(CALENDAR_ID)
);

-- CREATE SEQUENCE FOR FD_SKILL_MASTER TABLE
CREATE SEQUENCE SKILL_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_SKILL_MASTER TABLE
CREATE TABLE FD_SKILL_MASTER (
    SKILL_ID BIGINT PRIMARY KEY DEFAULT nextval('SKILL_SEQ'),
    SKILL_NAME VARCHAR(100) NOT NULL UNIQUE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- CREATE SEQUENCE FOR FD_AGENT_MASTER TABLE
CREATE SEQUENCE AGENT_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_AGENT_MASTER TABLE
CREATE TABLE FD_AGENT_MASTER (
    AGENT_ID BIGINT PRIMARY KEY DEFAULT nextval('AGENT_SEQ'),
    AGENT_NAME VARCHAR(255) NOT NULL UNIQUE,
    MAIL_ID VARCHAR(100) NOT NULL,
    ACCESS_ID VARCHAR(100) NOT NULL,
    USER_ID BIGINT NOT NULL UNIQUE,
    COMPANY_ID BIGINT,
    CALENDAR_ID BIGINT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_AGENT_USER FOREIGN KEY (USER_ID)
        REFERENCES FD_USER(USER_ID),
    CONSTRAINT FK_AGENT_COMPANY FOREIGN KEY (COMPANY_ID)
        REFERENCES FD_COMPANY_MASTER(COMPANY_ID),
    CONSTRAINT FK_AGENT_CALENDAR FOREIGN KEY (CALENDAR_ID)
        REFERENCES FD_CALENDAR_MASTER(CALENDAR_ID)
);
	
-- CREATE SEQUENCE FOR FD_AGENT_SKILLS TABLE
CREATE SEQUENCE AGENT_SKILL_SEQ
    START WITH 1
    INCREMENT BY 1;
	
-- CREATE FD_AGENT_SKILLS TABLE
CREATE TABLE FD_AGENT_SKILLS_MAPPING (
    AGENT_SKILL_ID BIGINT PRIMARY KEY DEFAULT nextval('AGENT_SKILL_SEQ'),
    AGENT_ID BIGINT NOT NULL,
    SKILL_ID BIGINT NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
	EXPERIENCE_YEARS INT NOT NULL,
	EXPERIENCE_MONTHS INT NOT NULL,
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_AGENT_SKILL_AGENT FOREIGN KEY (AGENT_ID)
        REFERENCES FD_AGENT_MASTER(AGENT_ID),
    CONSTRAINT FK_AGENT_SKILL_SKILL FOREIGN KEY (SKILL_ID)
        REFERENCES FD_SKILL_MASTER(SKILL_ID),
    UNIQUE (AGENT_ID, SKILL_ID)
);

-- CREATE SEQUENCE FOR FD_PRIORITY_MASTER TABLE
CREATE SEQUENCE PRIORITY_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_PRIORITY_MASTER TABLE
CREATE TABLE FD_PRIORITY_MASTER (
    PRIORITY_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('PRIORITY_SEQ'),
    PRIORITY_NAME VARCHAR(100) NOT NULL,
    COMPANY_ID BIGINT NOT NULL,
    RANK INT NOT NULL,
    COLOR_CODE VARCHAR(20), -- E.G., HEX (#FF0000) OR PREDEFINED LABEL
    RESPONSE_SLA INT NOT NULL, -- TIME BETWEEN CREATION AND ASSIGNMENT
	RESOLUTION_SLA INT NOT NULL, -- TIME BETWEEN CREATION AND TOTAL COMPLETION
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,	
    CONSTRAINT FK_PRIORITY_COMPANY FOREIGN KEY (COMPANY_ID)
        REFERENCES FD_COMPANY_MASTER(COMPANY_ID)
);

-- CREATE SEQUENCE FOR FD_BUSINESS_SERVICE TABLE
CREATE SEQUENCE BUSINESS_SERVICE_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_BUSINESS_SERVICE TABLE
CREATE TABLE FD_BUSINESS_SERVICE (
    SERVICE_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('BUSINESS_SERVICE_SEQ'),
    SERVICE_NAME VARCHAR(150) NOT NULL UNIQUE,   -- e.g., "Banking", "Insurance", "Travel"
    IS_ACTIVE BOOLEAN DEFAULT TRUE,              -- status flag
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- CREATE SEQUENCE FOR FD_SERVICE_OFFERING TABLE
CREATE SEQUENCE SERVICE_OFFERING_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_SERVICE_OFFERING TABLE
CREATE TABLE FD_SERVICE_OFFERING (
    OFFERING_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('SERVICE_OFFERING_SEQ'),
    SERVICE_ID BIGINT NOT NULL,                  -- FK to FD_BUSINESS_SERVICE
    OFFERING_NAME VARCHAR(150) NOT NULL,         -- e.g., "Savings Account", "Health Insurance"
    IS_ACTIVE BOOLEAN DEFAULT TRUE,              -- status flag
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_OFFERING_SERVICE FOREIGN KEY (SERVICE_ID) 
        REFERENCES FD_BUSINESS_SERVICE(SERVICE_ID)
);

-- CREATE SEQUENCE FD_REQUEST_CONFIG FD_SERVICE_OFFERING TABLE
CREATE SEQUENCE REQUEST_CONFIG_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_REQUEST_CONFIG TABLE
CREATE TABLE FD_REQUEST_CONFIG (
    CONFIG_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('REQUEST_CONFIG_SEQ'),
    REQUEST_TYPE VARCHAR(10) NOT NULL,   -- 'RITM' or 'INC'
    REQUEST_PREFIX VARCHAR(20) NOT NULL, -- e.g., "RITM", "INC"
    REVISION INT NOT NULL,
    RANGE_FROM INT NOT NULL,
    RANGE_TO INT NOT NULL,
    CALCULATE_BACKWARD BOOLEAN DEFAULT FALSE,
    PLANT_ID BIGINT NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,              -- status flag
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_REQUEST_CONFIG_PLANT FOREIGN KEY (PLANT_ID)
        REFERENCES FD_PLANT_MASTER(PLANT_ID)
);
