-- CREATE DATABASE FLICKZZ_DESK_LOCAL;
--/#psql
-- CREATE SEQUENCE FOR FD_COUNTRY_MASTER TABLE
CREATE SEQUENCE COUNTRY_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_COUNTRY_MASTER TABLE
CREATE TABLE FD_COUNTRY_MASTER (
    COUNTRY_ID BIGINT PRIMARY KEY DEFAULT nextval('COUNTRY_SEQ'),
    COUNTRY_NAME VARCHAR(100) NOT NULL UNIQUE,
    ISO_CODE VARCHAR(3) NOT NULL UNIQUE,
	PHONE_CODE VARCHAR(10) NOT NULL,
	CURRENCY_CODE VARCHAR(10), -- INR, USD 
	CURRENCY_NAME VARCHAR(50), 
	TIMEZONE VARCHAR(100),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- CREATE SEQUENCE FOR FD_STATE_MASTER TABLE
CREATE SEQUENCE STATE_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_STATE_MASTER TABLE
CREATE TABLE FD_STATE_MASTER (
    STATE_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('STATE_SEQ'),
    STATE_NAME VARCHAR(100) NOT NULL UNIQUE,
    STATE_CODE VARCHAR(10) UNIQUE,               -- OPTIONAL SHORT CODE (E.G., TN, CA)
    COUNTRY_ID BIGINT NOT NULL,                  -- FK TO FD_COUNTRY_MASTER
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_STATE_COUNTRY FOREIGN KEY (COUNTRY_ID)
        REFERENCES FD_COUNTRY_MASTER(COUNTRY_ID)
);

-- CREATE SEQUENCE FOR FD_CITY_MASTER TABLE
CREATE SEQUENCE CITY_SEQ
    START WITH 1
    INCREMENT BY 1;

-- UPDATE FD_CITY_MASTER TO LINK TO STATE INSTEAD OF JUST COUNTRY
CREATE TABLE FD_CITY_MASTER (
    CITY_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('CITY_SEQ'),
    CITY_NAME VARCHAR(100) NOT NULL,
    CITY_CODE VARCHAR(50) UNIQUE NOT NULL,
    STATE_ID BIGINT NOT NULL,                    -- FK TO FD_STATE_MASTER
    COUNTRY_ID BIGINT NOT NULL,                  -- REDUNDANT BUT USEFUL FOR REPORTING
    TIMEZONE VARCHAR(100),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CITY_STATE FOREIGN KEY (STATE_ID)
        REFERENCES FD_STATE_MASTER(STATE_ID),
    CONSTRAINT FK_CITY_COUNTRY FOREIGN KEY (COUNTRY_ID)
        REFERENCES FD_COUNTRY_MASTER(COUNTRY_ID)
);

-- CREATE SEQUENCE FOR FD_LANGUAGE_MASTER TABLE
CREATE SEQUENCE LANGUAGE_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_LANGUAGE_MASTER TABLE
CREATE TABLE FD_LANGUAGE_MASTER (
    LANGUAGE_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('LANGUAGE_SEQ'),
    LANGUAGE_NAME VARCHAR(100) NOT NULL UNIQUE,   -- FULL NAME (E.G., ENGLISH, HINDI)
    LANGUAGE_CODE VARCHAR(10) NOT NULL UNIQUE,    -- ISO CODE (E.G., EN, HI)
    IS_ACTIVE BOOLEAN DEFAULT TRUE,               -- STATUS FLAG
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- CREATE SEQUENCE FD_USER
CREATE SEQUENCE USER_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_USER TABLE
CREATE TABLE FD_USER (
    USER_ID BIGINT PRIMARY KEY DEFAULT nextval('USER_SEQ'),
    USER_NAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(50),
    MIDDLE_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    REGISTER_ID VARCHAR(50),
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    ROLE VARCHAR(100) NOT NULL,
    PHONE_CODE VARCHAR(10),
    PHONE_NUMBER VARCHAR(20) UNIQUE NOT NULL,
    COUNTRY_ID BIGINT,
    CITY_ID BIGINT,
    LANGUAGE_ID BIGINT,
    MFA_ENABLED BOOLEAN NOT NULL,
    SECRET VARCHAR(255),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50) DEFAULT 'SYSTEM',
    UPDATED_BY VARCHAR(50) DEFAULT 'SYSTEM',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT FK_USER_COUNTRY FOREIGN KEY (COUNTRY_ID)
        REFERENCES FD_COUNTRY_MASTER(COUNTRY_ID),
    CONSTRAINT FK_USER_CITY FOREIGN KEY (CITY_ID)
        REFERENCES FD_CITY_MASTER(CITY_ID),
    CONSTRAINT FK_USER_LANGUAGE FOREIGN KEY (LANGUAGE_ID)
        REFERENCES FD_LANGUAGE_MASTER(LANGUAGE_ID)
);

-- CREATE SEQUENCE FOR FD_COMPANY_MASTER TABLE
CREATE SEQUENCE COMPANY_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_COMPANY_MASTER TABLE
CREATE TABLE FD_COMPANY_MASTER (
    COMPANY_ID BIGINT PRIMARY KEY DEFAULT nextval('COMPANY_SEQ'),
    COMPANY_NAME VARCHAR(255) NOT NULL UNIQUE,
    PHONE_CODE VARCHAR(10),
    REGISTERED_NUMBER VARCHAR(100) NOT NULL,
    UID VARCHAR(100) NOT NULL UNIQUE,
    COUNTRY_ID BIGINT NOT NULL,
    STATE_ID BIGINT,
    CITY_ID BIGINT,
    PIN_CODE VARCHAR(20),
    EMPLOYEE_SIZE INT,
    ADDRESS_LINE_1 VARCHAR(255),
    ADDRESS_LINE_2 VARCHAR(255),
    MAIL VARCHAR(100) NOT NULL UNIQUE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,	
    CONSTRAINT FK_COMPANY_COUNTRY FOREIGN KEY (COUNTRY_ID)
        REFERENCES FD_COUNTRY_MASTER(COUNTRY_ID),
    CONSTRAINT FK_COMPANY_STATE FOREIGN KEY (STATE_ID)
        REFERENCES FD_STATE_MASTER(STATE_ID),
    CONSTRAINT FK_COMPANY_CITY FOREIGN KEY (CITY_ID)
        REFERENCES FD_CITY_MASTER(CITY_ID)
);

-- CREATE SEQUENCE FOR FD_COMPANY_ROLES TABLE
CREATE SEQUENCE COMPANY_ROLE_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_COMPANY_ROLES TABLE
CREATE TABLE FD_COMPANY_ROLES (
    ROLE_ID BIGINT PRIMARY KEY DEFAULT nextval('COMPANY_ROLE_SEQ'),
	COMPANY_ID BIGINT NOT NULL,
    MAPPING_ID BIGINT NOT NULL,
    IS_SERVICE_PROVIDER BOOLEAN DEFAULT FALSE,
    IS_REQUESTOR BOOLEAN DEFAULT FALSE,
    IS_BOTH BOOLEAN DEFAULT FALSE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_COMPANY_ROLE_COMPANY FOREIGN KEY (COMPANY_ID)
        REFERENCES FD_COMPANY_MASTER(COMPANY_ID),
    CONSTRAINT FK_COMPANY_ROLE_MAPPING_COMPANY FOREIGN KEY (MAPPING_ID)
        REFERENCES FD_COMPANY_MASTER(COMPANY_ID),
    CONSTRAINT UQ_COMPANY_ROLE_MAPPING UNIQUE (COMPANY_ID, MAPPING_ID)
);

-- CREATE SEQUENCE FD_ENQUIRY_REGISTRATION TABLE
CREATE SEQUENCE ENQUIRY_REG_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_ENQUIRY_REGISTRATION TABLE
CREATE TABLE FD_ENQUIRY_REGISTRATION (
    ENQUIRY_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('ENQUIRY_REG_SEQ'),
    FIRST_NAME VARCHAR(100) NOT NULL,
    MIDDLE_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100) NOT NULL,
    USER_NAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255),
    USER_ROLE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL,
    COMPANY_ID BIGINT NOT NULL,
    PHONE_CODE VARCHAR(10),
    PHONE_NUMBER VARCHAR(20),
    COUNTRY_ID BIGINT,                     -- FK TO FD_COUNTRY_MASTER (IF YOU HAVE ONE)
    STATE_ID BIGINT,
    CITY_ID BIGINT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,

    CONSTRAINT FK_ENQUIRY_COUNTRY FOREIGN KEY (COUNTRY_ID) REFERENCES FD_COUNTRY_MASTER(COUNTRY_ID),
    CONSTRAINT FK_ENQUIRY_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES FD_COMPANY_MASTER(COMPANY_ID),
    CONSTRAINT FK_ENQUIRY_STATE FOREIGN KEY (STATE_ID) REFERENCES FD_STATE_MASTER(STATE_ID),
    CONSTRAINT FK_ENQUIRY_CITY FOREIGN KEY (CITY_ID) REFERENCES FD_CITY_MASTER(CITY_ID)
);

-- CREATE SEQUENCE FD_ENQUIRY_INFO TABLE
CREATE SEQUENCE ENQUIRY_INFO_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_ENQUIRY_INFO TABLE
CREATE TABLE FD_ENQUIRY_INFO (
    ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('ENQUIRY_INFO_SEQ'),
    TOKEN VARCHAR(255) NOT NULL UNIQUE,       -- SECURE RANDOM TOKEN (UUID/JWT)
    ENQUIRY_ID BIGINT NOT NULL,               -- FK TO FD_ENQUIRY_REGISTRATION
    EXPIRY_TIME TIMESTAMP NOT NULL,           -- VALID UNTIL (E.G., 3 HOURS FROM CREATION)
    IS_USED BOOLEAN DEFAULT FALSE,            -- FLAG TO MARK IF TOKEN ALREADY CONSUMED
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_ENQUIRY_INFO_REGISTRATION FOREIGN KEY (ENQUIRY_ID) REFERENCES FD_ENQUIRY_REGISTRATION(ENQUIRY_ID)
);

-- CREATE SEQUENCE FD_AUTH
CREATE SEQUENCE AUTH_SEQ
    START WITH 1
    INCREMENT BY 1;
    
-- CREATE FD_AUTH TABLE
CREATE TABLE FD_AUTH (
    AUTH_ID BIGINT PRIMARY KEY DEFAULT nextval('AUTH_SEQ'),
    TOKEN VARCHAR(255) NOT NULL UNIQUE,
    EXPIRES_AT TIMESTAMP NOT NULL,
    USER_ID BIGINT,
    ENQUIRY_ID BIGINT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50) DEFAULT 'SYSTEM',
    UPDATED_BY VARCHAR(50) DEFAULT 'SYSTEM',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FD_USERS_REFRESH_TOKEN FOREIGN KEY (USER_ID)
        REFERENCES FD_USER(USER_ID),
    CONSTRAINT FD_ENQUIRY_REFRESH_TOKEN FOREIGN KEY (ENQUIRY_ID)
        REFERENCES FD_ENQUIRY_REGISTRATION(ENQUIRY_ID)
);

-- CREATE SEQUENCE FD_LOGIN_MASTER
CREATE SEQUENCE LOGIN_SEQ 
	START WITH 1 
	INCREMENT BY 1;

-- CREATE FD_LOGIN_MASTER TABLE
CREATE TABLE FD_LOGIN_MASTER (
    LOGIN_ID BIGINT PRIMARY KEY DEFAULT nextval('LOGIN_SEQ'),
    USER_NAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL UNIQUE,
    ROLE VARCHAR(100) NOT NULL,
    LAST_LOGIN_DATETIME TIMESTAMP,
    USER_ID BIGINT NOT NULL UNIQUE,
    AUTH_ID BIGINT UNIQUE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50) DEFAULT 'SYSTEM',
    UPDATED_BY VARCHAR(50) DEFAULT 'SYSTEM',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_LOGIN_USER FOREIGN KEY (USER_ID)
        REFERENCES FD_USER(USER_ID),
    CONSTRAINT FK_LOGIN_AUTH FOREIGN KEY (AUTH_ID)
        REFERENCES FD_AUTH(AUTH_ID)
);

-- CREATE SEQUENCE FOR FD_CALENDAR_TYPE TABLE
CREATE SEQUENCE CALENDAR_TYPE_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_CALENDAR_TYPE TABLE
CREATE TABLE FD_CALENDAR_TYPE (
    CALENDAR_TYPE_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('CALENDAR_TYPE_SEQ'),
    TYPE_NAME VARCHAR(100) NOT NULL,            -- Human-readable name
	COMPANY_ID BIGINT NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,             -- Active/inactive flag
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CALENDAR_TYPE_COMPANY FOREIGN KEY (COMPANY_ID)
        REFERENCES FD_COMPANY_MASTER(COMPANY_ID)
);

-- CREATE SEQUENCE FOR FD_CALENDAR_MASTER TABLE
CREATE SEQUENCE CALENDAR_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_CALENDAR_MASTER TABLE
CREATE TABLE FD_CALENDAR_MASTER (
    CALENDAR_ID BIGINT PRIMARY KEY DEFAULT nextval('CALENDAR_SEQ'),
    CALENDAR_CODE VARCHAR(20) NOT NULL,
    CALENDAR_TYPE_ID BIGINT NOT NULL,
    VALID_FROM TIMESTAMP NOT NULL,   -- YYYY
    VALID_TO TIMESTAMP NOT NULL,     -- YYYY
    WORK_FROM VARCHAR(10),       -- HH:mm stored as TIMESTAMP
    WORK_TO VARCHAR(10),         -- HH:mm stored as TIMESTAMP
    TIMEZONE VARCHAR(50),
	COMPANY_ID BIGINT NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT FK_CALENDAR_TYPE FOREIGN KEY (CALENDAR_TYPE_ID)
        REFERENCES FD_CALENDAR_TYPE(CALENDAR_TYPE_ID),
    CONSTRAINT FK_CALENDAR_COMPANY FOREIGN KEY (COMPANY_ID)
        REFERENCES FD_COMPANY_MASTER(COMPANY_ID),
    CONSTRAINT UQ_CALENDAR_CODE_COMPANY UNIQUE (CALENDAR_CODE, COMPANY_ID)
);

-- CREATE SEQUENCE FOR FD_SUBMENU TABLE
CREATE SEQUENCE CALENDAR_HOLIDAY_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_CALENDAR_HOLIDAY TABLE
CREATE TABLE FD_CALENDAR_HOLIDAY (
    HOLIDAY_ID BIGINT PRIMARY KEY DEFAULT nextval('CALENDAR_HOLIDAY_SEQ'),
    HOLIDAY_DATE TIMESTAMP NOT NULL,       -- DD.MM.YYYY format
    DESCRIPTION VARCHAR(255),
    CALENDAR_ID BIGINT NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT FD_CALENDAR_HOLIDAY FOREIGN KEY (CALENDAR_ID)
        REFERENCES FD_CALENDAR_MASTER(CALENDAR_ID)
);

-- CREATE SEQUENCE FOR FD_CALENDAR_WORKDAYS TABLE
CREATE SEQUENCE WORKDAY_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_CALENDAR_WORKDAYS TABLE
CREATE TABLE FD_CALENDAR_WORKDAYS (
    WORKDAY_ID BIGINT PRIMARY KEY DEFAULT nextval('WORKDAY_SEQ'),
    WORKDAY VARCHAR(20) NOT NULL,       -- e.g., "Monday", "Tuesday"
    CALENDAR_ID BIGINT NOT NULL,        -- FK to FD_CALENDAR_MASTER
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT FK_WORKDAY_CALENDAR FOREIGN KEY (CALENDAR_ID)
        REFERENCES FD_CALENDAR_MASTER(CALENDAR_ID)
);

-- CREATE SEQUENCE FOR FD_PLANT_MASTER TABLE
CREATE SEQUENCE PLANT_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_PLANT_MASTER TABLE
CREATE TABLE FD_PLANT_MASTER (
    PLANT_ID BIGINT PRIMARY KEY DEFAULT nextval('PLANT_SEQ'),
    PLANT_NAME VARCHAR(255) NOT NULL,
    COUNTRY_ID BIGINT NOT NULL,
    CALENDAR_ID BIGINT NOT NULL,
    COMPANY_ID BIGINT NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PLANT_COUNTRY FOREIGN KEY (COUNTRY_ID)
        REFERENCES FD_COUNTRY_MASTER(COUNTRY_ID),
    CONSTRAINT FK_PLANT_CALENDAR FOREIGN KEY (CALENDAR_ID)
        REFERENCES FD_CALENDAR_MASTER(CALENDAR_ID),
    CONSTRAINT FK_PLANT_COMPANY FOREIGN KEY (COMPANY_ID)
        REFERENCES FD_COMPANY_MASTER(COMPANY_ID),
    CONSTRAINT UQ_PLANT_NAME_COMPANY UNIQUE (PLANT_NAME, COMPANY_ID)
);

-- CREATE SEQUENCE FOR FD_SKILL_MASTER TABLE
CREATE SEQUENCE SKILL_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_SKILL_MASTER TABLE
CREATE TABLE FD_SKILL_MASTER (
    SKILL_ID BIGINT PRIMARY KEY DEFAULT nextval('SKILL_SEQ'),
    SKILL_NAME VARCHAR(100) NOT NULL,
    COMPANY_ID BIGINT NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SKILL_COMPANY FOREIGN KEY (COMPANY_ID)
        REFERENCES FD_COMPANY_MASTER(COMPANY_ID),
    CONSTRAINT UQ_SKILL_NAME_COMPANY UNIQUE (SKILL_NAME, COMPANY_ID)
);

-- CREATE SEQUENCE FOR FD_AGENT_MASTER TABLE
CREATE SEQUENCE AGENT_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_AGENT_MASTER TABLE
CREATE TABLE FD_AGENT_MASTER (
    AGENT_ID BIGINT PRIMARY KEY DEFAULT nextval('AGENT_SEQ'),
    AGENT_NAME VARCHAR(255) NOT NULL UNIQUE,
    MAIL_ID VARCHAR(100) NOT NULL,
    ACCESS_ID VARCHAR(100) NOT NULL,
    USER_ID BIGINT NOT NULL UNIQUE,
    COMPANY_ID BIGINT,
    CALENDAR_ID BIGINT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_AGENT_USER FOREIGN KEY (USER_ID)
        REFERENCES FD_USER(USER_ID),
    CONSTRAINT FK_AGENT_COMPANY FOREIGN KEY (COMPANY_ID)
        REFERENCES FD_COMPANY_MASTER(COMPANY_ID),
    CONSTRAINT FK_AGENT_CALENDAR FOREIGN KEY (CALENDAR_ID)
        REFERENCES FD_CALENDAR_MASTER(CALENDAR_ID)
);
	
-- CREATE SEQUENCE FOR FD_AGENT_SKILLS TABLE
CREATE SEQUENCE AGENT_SKILL_SEQ
    START WITH 1
    INCREMENT BY 1;
	
-- CREATE FD_AGENT_SKILLS TABLE
CREATE TABLE FD_AGENT_SKILLS_MAPPING (
    AGENT_SKILL_ID BIGINT PRIMARY KEY DEFAULT nextval('AGENT_SKILL_SEQ'),
    AGENT_ID BIGINT NOT NULL,
    SKILL_ID BIGINT NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
	EXPERIENCE_YEARS INT NOT NULL,
	EXPERIENCE_MONTHS INT NOT NULL,
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_AGENT_SKILL_AGENT FOREIGN KEY (AGENT_ID)
        REFERENCES FD_AGENT_MASTER(AGENT_ID),
    CONSTRAINT FK_AGENT_SKILL_SKILL FOREIGN KEY (SKILL_ID)
        REFERENCES FD_SKILL_MASTER(SKILL_ID),
    UNIQUE (AGENT_ID, SKILL_ID)
);

-- CREATE SEQUENCE FOR FD_PRIORITY_MASTER TABLE
CREATE SEQUENCE PRIORITY_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_PRIORITY_MASTER TABLE
CREATE TABLE FD_PRIORITY_MASTER (
    PRIORITY_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('PRIORITY_SEQ'),
    PRIORITY_NAME VARCHAR(100) NOT NULL,
    COMPANY_ID BIGINT NOT NULL,
    RANK INT NOT NULL,
    COLOR_CODE VARCHAR(20), -- E.G., HEX (#FF0000) OR PREDEFINED LABEL
    RESPONSE_SLA INT NOT NULL, -- TIME BETWEEN CREATION AND ASSIGNMENT
	RESOLUTION_SLA INT NOT NULL, -- TIME BETWEEN CREATION AND TOTAL COMPLETION
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,	
    CONSTRAINT FK_PRIORITY_COMPANY FOREIGN KEY (COMPANY_ID)
        REFERENCES FD_COMPANY_MASTER(COMPANY_ID)
);

-- CREATE SEQUENCE FOR FD_BUSINESS_SERVICE TABLE
CREATE SEQUENCE BUSINESS_SERVICE_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_BUSINESS_SERVICE TABLE
CREATE TABLE FD_BUSINESS_SERVICE (
    SERVICE_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('BUSINESS_SERVICE_SEQ'),
    SERVICE_NAME VARCHAR(150) NOT NULL UNIQUE,   -- e.g., "Banking", "Insurance", "Travel"
    COMPANY_ID BIGINT NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,              -- status flag
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_BUSINESS_SERVICE_COMPANY FOREIGN KEY (COMPANY_ID)
        REFERENCES FD_COMPANY_MASTER(COMPANY_ID)
);

-- CREATE SEQUENCE FOR FD_SERVICE_OFFERING TABLE
CREATE SEQUENCE SERVICE_OFFERING_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_SERVICE_OFFERING TABLE
CREATE TABLE FD_SERVICE_OFFERING (
    OFFERING_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('SERVICE_OFFERING_SEQ'),
    SERVICE_ID BIGINT NOT NULL,                  -- FK to FD_BUSINESS_SERVICE
    OFFERING_NAME VARCHAR(150) NOT NULL,         -- e.g., "Savings Account", "Health Insurance"
    IS_ACTIVE BOOLEAN DEFAULT TRUE,              -- status flag
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_OFFERING_SERVICE FOREIGN KEY (SERVICE_ID) 
        REFERENCES FD_BUSINESS_SERVICE(SERVICE_ID)
);

-- CREATE SEQUENCE FD_REQUEST_CONFIG TABLE
CREATE SEQUENCE REQUEST_CONFIG_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_REQUEST_CONFIG TABLE
CREATE TABLE FD_REQUEST_CONFIG (
    CONFIG_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('REQUEST_CONFIG_SEQ'),
    REQUEST_TYPE VARCHAR(10) NOT NULL,   -- 'RITM' or 'INC'
    REQUEST_PREFIX VARCHAR(20) NOT NULL, -- e.g., "RITM", "INC"
    REVISION INT NOT NULL,
    RANGE_FROM INT NOT NULL,
    RANGE_TO INT NOT NULL,
    CALCULATE_BACKWARD BOOLEAN DEFAULT FALSE,
    COMPANY_ID BIGINT NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,              -- status flag
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_REQUEST_CONFIG_COMPANY FOREIGN KEY (COMPANY_ID)
        REFERENCES FD_COMPANY_MASTER(COMPANY_ID)
);

-- CREATE SEQUENCE FD_IMPACT_MASTER TABLE
CREATE SEQUENCE IMPACT_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_IMPACT_MASTER TABLE
CREATE TABLE FD_IMPACT_MASTER (
    IMPACT_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('IMPACT_SEQ'),
    IMPACT_CODE      VARCHAR(50) NOT NULL UNIQUE,   -- E.G., LOW, MEDIUM, HIGH, CRITICAL
    IMPACT_LEVEL     INTEGER NOT NULL,              -- NUMERIC (1 = HIGHEST IMPACT)
    SLA_MULTIPLIER   NUMERIC(5,2) DEFAULT 1.00,     -- OPTIONAL: AFFECTS SLA CALCULATION
    COMPANY_ID BIGINT NOT NULL,
    IS_ACTIVE        BOOLEAN DEFAULT TRUE,
    CREATED_BY       VARCHAR(100),
    CREATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY       VARCHAR(100),
    UPDATED_AT       TIMESTAMP,
    CONSTRAINT FK_IMPACT_COMPANY FOREIGN KEY (COMPANY_ID)
        REFERENCES FD_COMPANY_MASTER(COMPANY_ID)
);

-- CREATE SEQUENCE FD_TICKET TABLE
CREATE SEQUENCE TICKET_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_TICKET TABLE
CREATE TABLE FD_TICKET (
    TICKET_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('TICKET_SEQ'),
    REQUEST_TYPE VARCHAR(10) NOT NULL,                -- 'RITM' OR 'INC'
    REQUEST_NUMBER VARCHAR(50) NOT NULL UNIQUE,
    OPENED_BY BIGINT NOT NULL,                -- FK TO FD_USER
    REQUESTED_FOR BIGINT NOT NULL,            -- FK TO FD_USER
    BUSINESS_SERVICE_ID BIGINT,               -- FK TO FD_BUSINESS_SERVICE
    SERVICE_OFFERING_ID BIGINT,               -- FK TO FD_SERVICE_OFFERING
    CONFIG_ITEM_GROUP VARCHAR(100),
    IMPACT_ID BIGINT,                         -- FK TO FD_IMPACT_MASTER
    PRIORITY_ID BIGINT,                       -- FK TO FD_PRIORITY_MASTER
    SHORT_DESCRIPTION VARCHAR(255),
    DESCRIPTION TEXT,
    ATTACHMENT VARCHAR(255),
    COMPANY_ID BIGINT NOT NULL,
    CREATED_BY       VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY       VARCHAR(100),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,

    CONSTRAINT FK_TICKET_OPENED_BY FOREIGN KEY (OPENED_BY) REFERENCES FD_USER(USER_ID),
    CONSTRAINT FK_TICKET_REQUESTED_FOR FOREIGN KEY (REQUESTED_FOR) REFERENCES FD_USER(USER_ID),
    CONSTRAINT FK_TICKET_BUSINESS_SERVICE FOREIGN KEY (BUSINESS_SERVICE_ID) REFERENCES FD_BUSINESS_SERVICE(SERVICE_ID),
    CONSTRAINT FK_TICKET_SERVICE_OFFERING FOREIGN KEY (SERVICE_OFFERING_ID) REFERENCES FD_SERVICE_OFFERING(OFFERING_ID),
    CONSTRAINT FK_TICKET_IMPACT FOREIGN KEY (IMPACT_ID) REFERENCES FD_IMPACT_MASTER(IMPACT_ID),
    CONSTRAINT FK_TICKET_PRIORITY FOREIGN KEY (PRIORITY_ID) REFERENCES FD_PRIORITY_MASTER(PRIORITY_ID),
    CONSTRAINT FK_TICKET_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES FD_COMPANY_MASTER(COMPANY_ID)
);

-- CREATE SEQUENCE FD_REQUEST_ITEM TABLE
CREATE SEQUENCE REQUEST_ITEM_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_REQUEST_ITEM TABLE
CREATE TABLE FD_REQUEST_ITEM (
    RITM_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('REQUEST_ITEM_SEQ'),
    TICKET_ID BIGINT NOT NULL,
    -- ADD RITM-SPECIFIC FIELDS HERE IF NEEDED (E.G., APPROVAL WORKFLOW, CATALOG ITEM)
    CONSTRAINT FK_RITM_TICKET FOREIGN KEY (TICKET_ID) REFERENCES FD_TICKET(TICKET_ID)
);

-- CREATE SEQUENCE FD_INCIDENT TABLE
CREATE SEQUENCE INCIDENT_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_INCIDENT TABLE
CREATE TABLE FD_INCIDENT (
    INCIDENT_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('INCIDENT_SEQ'),
    TICKET_ID BIGINT NOT NULL,
    -- ADD INC-SPECIFIC FIELDS HERE IF NEEDED (E.G., SEVERITY, RESOLUTION SLA)
    CONSTRAINT FK_INCIDENT_TICKET FOREIGN KEY (TICKET_ID) REFERENCES FD_TICKET(TICKET_ID)
);

-- CREATE SEQUENCE FD_TICKET_WATCHLIST TABLE
CREATE SEQUENCE TICKET_WATCHLIST_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_TICKET_WATCHLIST TABLE
CREATE TABLE FD_TICKET_WATCHLIST (
    MAPPING_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('TICKET_WATCHLIST_SEQ'),
    TICKET_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    CONSTRAINT FK_WATCHLIST_TICKET FOREIGN KEY (TICKET_ID) REFERENCES FD_TICKET(TICKET_ID),
    CONSTRAINT FK_WATCHLIST_USER FOREIGN KEY (USER_ID) REFERENCES FD_USER(USER_ID),
    CONSTRAINT UQ_TICKET_USER UNIQUE (TICKET_ID, USER_ID)
);

------------------- 08/05/2026 -------------------
-- CREATE SEQUENCE FOR FD_PROJECT TABLE
CREATE SEQUENCE PROJECT_SEQ START WITH 1 INCREMENT BY 1;

-- FD_PROJECT TABLE
CREATE TABLE FD_PROJECT (
    PROJECT_ID    BIGINT PRIMARY KEY DEFAULT nextval('PROJECT_SEQ'),
    COMPANY_ID     BIGINT,
    PROJECT_CD       VARCHAR(100),
    PROJECT_NAME  VARCHAR(255) NOT NULL,
    PROJECT_DESC	TEXT,
    PLANNED_START_DATE    TIMESTAMP,
    PLANNED_END_DATE      TIMESTAMP,
    ACTUAL_START_DATE    TIMESTAMP,
    ACTUAL_END_DATE      TIMESTAMP,
    IS_SAVED     BOOLEAN DEFAULT FALSE,
    IS_SUBMITED     BOOLEAN DEFAULT FALSE,
    IS_ACTIVE     BOOLEAN DEFAULT TRUE,
    CREATED_BY    VARCHAR(50),
    UPDATED_BY    VARCHAR(50),
    CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (COMPANY_ID) REFERENCES FD_COMPANY_MASTER(COMPANY_ID)
);

-- CREATE SEQUENCE FOR FD_PROGRESS_STATUS TABLE
CREATE SEQUENCE PROGRESS_STATUS_SEQ START WITH 1 INCREMENT BY 1;

-- FD_PROGRESS_STATUS TABLE (Dynamic progress tracking)
CREATE TABLE FD_PROGRESS_STATUS (
    PROGRESS_ID   BIGINT PRIMARY KEY DEFAULT nextval('PROGRESS_STATUS_SEQ'),
    COMPANY_ID     BIGINT,
    PROGRESS_NAME        VARCHAR(50),          -- NOT STARTED, IN PROGRESS, DONE
    PROGRESS_SEQUENCE  INTEGER NOT NULL,             -- SEQUENCE FOR ORDERING STATUSES
    COLOR_CODE         VARCHAR(20),            -- OPTIONAL: HEX OR PREDEFINED COLOR
    IS_ACTIVE     BOOLEAN DEFAULT TRUE,
    CREATED_BY    VARCHAR(50),
    CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY    VARCHAR(50),
    FOREIGN KEY (COMPANY_ID) REFERENCES FD_COMPANY_MASTER(COMPANY_ID)
);

-- CREATE SEQUENCE FOR FD_EPIC TABLE
CREATE SEQUENCE EPIC_SEQ START WITH 1 INCREMENT BY 1;

-- FD_EPIC TABLE
CREATE TABLE FD_EPIC (
    EPIC_ID       BIGINT PRIMARY KEY DEFAULT nextval('EPIC_SEQ'),
    PROJECT_ID    BIGINT,
    EPIC_NAME     VARCHAR(255) NOT NULL,
    EPIC_DESC	TEXT,
    EPIC_SEQUENCE INTEGER NOT NULL, 
	PROGRESS_ID		BIGINT NOT NULL,
	MAX_PROGRESS_NUMBER INTEGER NOT NULL,
    PLANNED_START_DATE    TIMESTAMP,
    PLANNED_END_DATE      TIMESTAMP,
    ACTUAL_START_DATE    TIMESTAMP,
    ACTUAL_END_DATE      TIMESTAMP,
    IS_ACTIVE     BOOLEAN DEFAULT TRUE,
    CREATED_BY    VARCHAR(50),
    UPDATED_BY    VARCHAR(50),
    CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PROJECT_ID) REFERENCES FD_PROJECT(PROJECT_ID),
    FOREIGN KEY (PROGRESS_ID) REFERENCES FD_PROGRESS_STATUS(PROGRESS_ID)
);

-- CREATE SEQUENCE FOR FD_USER_STORY TABLE
CREATE SEQUENCE USER_STORY_SEQ START WITH 1 INCREMENT BY 1;

-- FD_USER_STORY TABLE
CREATE TABLE FD_USER_STORY (
    STORY_ID      BIGINT PRIMARY KEY DEFAULT nextval('USER_STORY_SEQ'),
    EPIC_ID       BIGINT NOT NULL,
	PROGRESS_ID		BIGINT NOT NULL,
	MAX_PROGRESS_NUMBER INTEGER NOT NULL,
    STORY_CODE    VARCHAR(50),
    TITLE         VARCHAR(255),
    DESCRIPTION   TEXT,
    STORY_SEQUENCE INTEGER NOT NULL,
    AGENT_ID      BIGINT,
	PLANNED_START_DATE TIMESTAMP,
	PLANNED_END_DATE TIMESTAMP,
    ACTUAL_START_DATE    TIMESTAMP,
    ACTUAL_END_DATE      TIMESTAMP,
    PREDECESSOR_ID BIGINT,
    PRIORITY_ID    BIGINT,
    STORY_POINTS  INTEGER,
    IS_ACTIVE     BOOLEAN DEFAULT TRUE,
    CREATED_BY    VARCHAR(50),
    UPDATED_BY    VARCHAR(50),
    CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (EPIC_ID) REFERENCES FD_EPIC(EPIC_ID),
    FOREIGN KEY (PREDECESSOR_ID) REFERENCES FD_USER_STORY(STORY_ID),
    FOREIGN KEY (AGENT_ID) REFERENCES FD_AGENT_MASTER(AGENT_ID),
    FOREIGN KEY (PROGRESS_ID) REFERENCES FD_PROGRESS_STATUS(PROGRESS_ID),
    FOREIGN KEY (PRIORITY_ID) REFERENCES FD_PRIORITY_MASTER(PRIORITY_ID)
);

-- CREATE SEQUENCE FOR FD_TASK TABLE
CREATE SEQUENCE TASK_SEQ START WITH 1 INCREMENT BY 1;

-- FD_TASK TABLE
CREATE TABLE FD_TASK (
    TASK_ID       BIGINT PRIMARY KEY DEFAULT nextval('TASK_SEQ'),
    STORY_ID      BIGINT NOT NULL,
    AGENT_ID      BIGINT,
	PROGRESS_ID		BIGINT NOT NULL,
	MAX_PROGRESS_NUMBER INTEGER NOT NULL,
    TITLE         VARCHAR(255),
    DESCRIPTION   TEXT,
    TASK_SEQUENCE INTEGER NOT NULL,
	PLANNED_START_DATE	TIMESTAMP,
	PLANNED_END_DATE	TIMESTAMP,
    ACTUAL_START_DATE    TIMESTAMP,
    ACTUAL_END_DATE      TIMESTAMP,
    IS_ACTIVE     BOOLEAN DEFAULT TRUE,
    CREATED_BY    VARCHAR(50),
    UPDATED_BY    VARCHAR(50),
    CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (STORY_ID) REFERENCES FD_USER_STORY(STORY_ID),
    FOREIGN KEY (AGENT_ID) REFERENCES FD_AGENT_MASTER(AGENT_ID),
    FOREIGN KEY (PROGRESS_ID) REFERENCES FD_PROGRESS_STATUS(PROGRESS_ID)
);

-- CREATE SEQUENCE FOR FD_SUB_TASK TABLE
CREATE SEQUENCE SUB_TASK_SEQ START WITH 1 INCREMENT BY 1;

-- FD_SUB_TASK TABLE
CREATE TABLE FD_SUB_TASK (
    SUB_TASK_ID   BIGINT PRIMARY KEY DEFAULT nextval('SUB_TASK_SEQ'),
    TASK_ID       BIGINT NOT NULL,
	PROGRESS_ID		BIGINT NOT NULL,
	MAX_PROGRESS_NUMBER BIGINT NOT NULL, -- TRACKS THE HIGHEST PROGRESS STATUS REACHED (FOR REPORTING)
    AGENT_ID      BIGINT NOT NULL,
    TITLE         VARCHAR(255),
    DESCRIPTION   TEXT,
	PLANNED_START_DATE	TIMESTAMP,
	PLANNED_END_DATE	TIMESTAMP,
    ACTUAL_START_DATE    TIMESTAMP,
    ACTUAL_END_DATE      TIMESTAMP,
    IS_ACTIVE     BOOLEAN DEFAULT TRUE,
    CREATED_BY    VARCHAR(50),
    UPDATED_BY    VARCHAR(50),
    CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (TASK_ID) REFERENCES FD_TASK(TASK_ID),
    FOREIGN KEY (PROGRESS_ID) REFERENCES FD_PROGRESS_STATUS(PROGRESS_ID),
    FOREIGN KEY (AGENT_ID) REFERENCES FD_AGENT_MASTER(AGENT_ID)
);

-- CREATE SEQUENCE FOR FD_PROJECT_LEAD_ASSIGNMENT TABLE
CREATE SEQUENCE PROJECT_LEAD_SEQ START WITH 1 INCREMENT BY 1;

-- FD_PROJECT_LEAD_ASSIGNMENT TABLE
CREATE TABLE FD_PROJECT_LEAD_ASSIGNMENT (
    ASSIGNMENT_ID	BIGINT PRIMARY KEY DEFAULT nextval('PROJECT_LEAD_SEQ'),
    COMPANY_ID	BIGINT NOT NULL,
    STORY_ID	BIGINT NOT NULL,
    IS_ACTIVE     BOOLEAN DEFAULT TRUE,
    CREATED_BY    VARCHAR(50),
    UPDATED_BY    VARCHAR(50),
    CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_LEAD_ASSIGN_COMPANY
        FOREIGN KEY (COMPANY_ID)
        REFERENCES FD_COMPANY_MASTER(COMPANY_ID),

    CONSTRAINT FK_LEAD_ASSIGN_STORY
        FOREIGN KEY (STORY_ID)
        REFERENCES FD_USER_STORY(STORY_ID)
);

-- CREATE SEQUENCE FOR FD_WORK_ITEMS TABLE
CREATE SEQUENCE WORK_ITEM_SEQ START WITH 1 INCREMENT BY 1;

-- FD_WORK_ITEMS TABLE
CREATE TABLE FD_WORK_ITEMS (
    ITEM_ID BIGINT PRIMARY KEY DEFAULT nextval('WORK_ITEM_SEQ'),
    CODE VARCHAR(20) NOT NULL UNIQUE,
    LABEL VARCHAR(100) NOT NULL,
    IS_ACTIVE     BOOLEAN DEFAULT TRUE,
    CREATED_BY    VARCHAR(50),
    UPDATED_BY    VARCHAR(50),
    CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- CREATE SEQUENCE FOR FD_FIELD_TYPES TABLE
CREATE SEQUENCE FIELD_TYPE_SEQ START WITH 1 INCREMENT BY 1;

-- FD_FIELD_TYPES TABLE
CREATE TABLE FD_FIELD_TYPES (
    FIELD_ID BIGINT PRIMARY KEY DEFAULT nextval('FIELD_TYPE_SEQ'),
    CODE VARCHAR(50) NOT NULL UNIQUE,
    LABEL VARCHAR(100) NOT NULL,
    IS_ACTIVE     BOOLEAN DEFAULT TRUE,
    CREATED_BY    VARCHAR(50),
    UPDATED_BY    VARCHAR(50),
    CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- SEQUENCE FOR FD_TEMPLATE_DETAILS
CREATE SEQUENCE TEMPLATE_SEQ
    START WITH 1
    INCREMENT BY 1;

-- MAIN TEMPLATE TABLE
CREATE TABLE FD_TEMPLATE_DETAILS (
    TEMPLATE_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('TEMPLATE_SEQ'),
    TEMPLATE_NAME VARCHAR(255) NOT NULL,
    WORK_ITEM_ID BIGINT NOT NULL,
    COMPANY_ID BIGINT NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_TEMPLATE_COMPANY FOREIGN KEY (COMPANY_ID)
        REFERENCES FD_COMPANY_MASTER(COMPANY_ID),
    CONSTRAINT FK_TEMPLATE_WORK_ITEM FOREIGN KEY (WORK_ITEM_ID)
        REFERENCES FD_WORK_ITEMS(ITEM_ID),
    CONSTRAINT UQ_TEMPLATE_NAME_COMPANY UNIQUE (TEMPLATE_NAME, COMPANY_ID)
);

-- SEQUENCE FOR FD_TEMPLATE_DETAIL_FIELD
CREATE SEQUENCE TEMPLATE_FIELD_SEQ
    START WITH 1
    INCREMENT BY 1;

-- TEMPLATE FIELD TABLE
CREATE TABLE FD_TEMPLATE_DETAIL_FIELD (
    FIELD_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('TEMPLATE_FIELD_SEQ'),
    TEMPLATE_ID BIGINT NOT NULL,
    FIELD_NAME VARCHAR(255) NOT NULL,
    FIELD_TYPE_ID BIGINT NOT NULL,
    MANDATORY BOOLEAN DEFAULT FALSE,
    FIELD_SEQUENCE INT NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_FIELD_TEMPLATE FOREIGN KEY (TEMPLATE_ID)
        REFERENCES FD_TEMPLATE_DETAILS(TEMPLATE_ID),
    CONSTRAINT FK_FIELD_FIELD_TYPE FOREIGN KEY (FIELD_TYPE_ID)
        REFERENCES FD_FIELD_TYPES(FIELD_ID),
    CONSTRAINT UQ_TEMPLATE_FIELD_SEQUENCE UNIQUE (TEMPLATE_ID, FIELD_SEQUENCE)
);

-- SEQUENCE FOR FD_TEMPLATE_FIELD_OPTION
CREATE SEQUENCE FIELD_OPTION_SEQ
    START WITH 1
    INCREMENT BY 1;

-- FIELD OPTION TABLE
CREATE TABLE FD_TEMPLATE_FIELD_OPTION (
    OPTION_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('FIELD_OPTION_SEQ'),
    FIELD_ID BIGINT NOT NULL,
    LABEL VARCHAR(255) NOT NULL,
    VALUE VARCHAR(255),
    DEFAULT_SELECTED BOOLEAN DEFAULT FALSE,
    OPTION_SEQUENCE INT NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_OPTION_FIELD FOREIGN KEY (FIELD_ID)
        REFERENCES FD_TEMPLATE_DETAIL_FIELD(FIELD_ID),
    CONSTRAINT UQ_FIELD_OPTION_SEQUENCE UNIQUE (FIELD_ID, OPTION_SEQUENCE)
);
