CREATE DATABASE FLICKZZ_DESK_LOCAL;

-- CREATE SEQUENCE FD_USER
CREATE SEQUENCE USER_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_USER TABLE
CREATE TABLE FD_USER (
    USER_ID BIGINT PRIMARY KEY DEFAULT nextval('USER_SEQ'),
    USER_NAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(50) NOT NULL UNIQUE,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50).
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    ROLE VARCHAR(100) NOT NULL,
    MFA_ENABLED BOOLEAN NOT NULL,
    SECRET VARCHAR(255),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50) DEFAULT 'SYSTEM',
    UPDATED_BY VARCHAR(50) DEFAULT 'SYSTEM',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- CREATE SEQUENCE AUTH
CREATE SEQUENCE AUTH_SEQ
    START WITH 1
    INCREMENT BY 1;
    
-- CREATE AUTH TABLE
CREATE TABLE AUTH (
    AUTH_ID BIGINT PRIMARY KEY DEFAULT nextval('AUTH_SEQ'),
    TOKEN VARCHAR(255) NOT NULL UNIQUE,
    EXPIRES_AT TIMESTAMP NOT NULL,
    USER_ID BIGINT NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50) DEFAULT 'SYSTEM',
    UPDATED_BY VARCHAR(50) DEFAULT 'SYSTEM',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FD_USERS_REFRESH_TOKEN FOREIGN KEY (USER_ID)
        REFERENCES FD_USER(USER_ID)
);

-- CREATE SEQUENCE LOGIN_MASTER
CREATE SEQUENCE LOGIN_SEQ 
	START WITH 1 
	INCREMENT BY 1;

-- CREATE LOGIN_MASTER TABLE
CREATE TABLE LOGIN_MASTER (
    LOGIN_ID BIGINT PRIMARY KEY DEFAULT nextval('LOGIN_SEQ'),
    USER_NAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL UNIQUE,
    ROLE VARCHAR(100) NOT NULL,
    LAST_LOGIN_DATETIME TIMESTAMP,
    USER_ID BIGINT NOT NULL UNIQUE,
    AUTH_ID BIGINT UNIQUE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50) DEFAULT 'SYSTEM',
    UPDATED_BY VARCHAR(50) DEFAULT 'SYSTEM',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_LOGIN_USER FOREIGN KEY (USER_ID)
        REFERENCES FD_USER(USER_ID),
    CONSTRAINT FK_LOGIN_AUTH FOREIGN KEY (AUTH_ID)
        REFERENCES AUTH(AUTH_ID)
);

-- CREATE SEQUENCE FOR FD_CALENDAR_MASTER TABLE
CREATE SEQUENCE CALENDAR_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_CALENDAR_MASTER TABLE
CREATE TABLE FD_CALENDAR_MASTER (
    CALENDAR_ID BIGINT PRIMARY KEY DEFAULT nextval('CALENDAR_SEQ'),
    CALENDAR_CODE VARCHAR(20) NOT NULL UNIQUE,
    CALENDAR_TYPE VARCHAR(20) NOT NULL,
    VALID_FROM TIMESTAMP NOT NULL,   -- YYYY
    VALID_TO TIMESTAMP NOT NULL,     -- YYYY
    WORK_FROM VARCHAR(10),       -- HH:mm stored as TIMESTAMP
    WORK_TO VARCHAR(10),         -- HH:mm stored as TIMESTAMP
    TIMEZONE VARCHAR(50),
	IS_SUPPORT BOOLEAN DEFAULT FALSE,
	IS_REQUESTOR BOOLEAN DEFAULT FALSE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);

-- CREATE SEQUENCE FOR FD_SUBMENU TABLE
CREATE SEQUENCE CALENDAR_HOLIDAY_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_CALENDAR_HOLIDAY TABLE
CREATE TABLE FD_CALENDAR_HOLIDAY (
    HOLIDAY_ID BIGINT PRIMARY KEY DEFAULT nextval('CALENDAR_HOLIDAY_SEQ'),
    HOLIDAY_DATE TIMESTAMP NOT NULL,       -- DD.MM.YYYY format
    DESCRIPTION VARCHAR(255),
    CALENDAR_ID BIGINT NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT FD_CALENDAR_HOLIDAY FOREIGN KEY (CALENDAR_ID)
        REFERENCES FD_CALENDAR_MASTER(CALENDAR_ID)
);

-- CREATE SEQUENCE FOR FD_CALENDAR_WORKDAYS TABLE
CREATE SEQUENCE WORKDAY_SEQ
    START WITH 1
    INCREMENT BY 1;

-- CREATE FD_CALENDAR_WORKDAYS TABLE
CREATE TABLE FD_CALENDAR_WORKDAYS (
    WORKDAY_ID BIGINT PRIMARY KEY DEFAULT nextval('WORKDAY_SEQ'),
    WORKDAY VARCHAR(20) NOT NULL,       -- e.g., "Monday", "Tuesday"
    CALENDAR_ID BIGINT NOT NULL,        -- FK to FD_CALENDAR_MASTER
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT FK_WORKDAY_CALENDAR FOREIGN KEY (CALENDAR_ID)
        REFERENCES FD_CALENDAR_MASTER(CALENDAR_ID)
);

-- Insert dummy user
INSERT INTO FD_USER (USER_NAME, PASSWORD, ROLE) 
VALUES ('flickzz', '2018', 'ADMIN');
