
INSERT INTO FD_PROGRESS_STATUS 
    (COMPANY_ID, PROGRESS_NAME, PROGRESS_SEQUENCE, COLOR_CODE, IS_ACTIVE, CREATED_BY, IS_CREATOR_ADMIN)
VALUES
    (20, 'NOT STARTED', 1, '#FF0000', TRUE, 20, true);
    
INSERT INTO FD_PROGRESS_STATUS 
    (COMPANY_ID, PROGRESS_NAME, PROGRESS_SEQUENCE, COLOR_CODE, IS_ACTIVE, CREATED_BY, IS_CREATOR_ADMIN)
VALUES
    (20, 'PRIORITIZED', 2, '#FFFF00', TRUE, 20, true);

INSERT INTO FD_PROGRESS_STATUS 
    (COMPANY_ID, PROGRESS_NAME, PROGRESS_SEQUENCE, COLOR_CODE, IS_ACTIVE, CREATED_BY, IS_CREATOR_ADMIN)
VALUES
    (20, 'In Test', 5, '#F59E0B', TRUE, 20, true);

INSERT INTO FD_PROGRESS_STATUS 
    (COMPANY_ID, PROGRESS_NAME, PROGRESS_SEQUENCE, COLOR_CODE, IS_ACTIVE, CREATED_BY, IS_CREATOR_ADMIN)
VALUES
    (20, 'Blocked', 6, '#F44336', TRUE, 20, true);


-- Company 1 acts only as a Service Provider
INSERT INTO FD_COMPANY_ROLES (
    COMPANY_ID, MAPPING_ID, IS_SERVICE_PROVIDER, IS_REQUESTOR, IS_BOTH, IS_ACTIVE, CREATED_BY, IS_CREATOR_ADMIN
) VALUES (
    20, 20, FALSE, FALSE, TRUE, TRUE, 20, true
);

-- Company 2 acts only as a Requestor
INSERT INTO FD_COMPANY_ROLES (
    COMPANY_ID, MAPPING_ID, IS_SERVICE_PROVIDER, IS_REQUESTOR, IS_BOTH, IS_ACTIVE, CREATED_BY, IS_CREATOR_ADMIN
) VALUES (
    20, 2, TRUE, FALSE, FALSE, TRUE, 20, true
);

-- Company 3 acts as Both (Service Provider + Requestor)
INSERT INTO FD_COMPANY_ROLES (
    COMPANY_ID, MAPPING_ID, IS_SERVICE_PROVIDER, IS_REQUESTOR, IS_BOTH, IS_ACTIVE, CREATED_BY, IS_CREATOR_ADMIN
) VALUES (
    20, 4, TRUE, FALSE, FALSE, TRUE, 20, true
);


-- Company 3 acts as Both (Service Provider + Requestor)
INSERT INTO FD_COMPANY_ROLES (
    COMPANY_ID, MAPPING_ID, IS_SERVICE_PROVIDER, IS_REQUESTOR, IS_BOTH, IS_ACTIVE, CREATED_BY, IS_CREATOR_ADMIN
) VALUES (
    20, 13, TRUE, FALSE, FALSE, TRUE, 20, true
);
