
INSERT INTO FD_PROGRESS_STATUS 
    (COMPANY_ID, PROGRESS_NAME, PROGRESS_SEQUENCE, COLOR_CODE, IS_ACTIVE, CREATED_BY, UPDATED_BY)
VALUES
    (4, 'NOT STARTED', 1, '#FF0000', TRUE, 'system', 'system');
    
INSERT INTO FD_PROGRESS_STATUS 
    (COMPANY_ID, PROGRESS_NAME, PROGRESS_SEQUENCE, COLOR_CODE, IS_ACTIVE, CREATED_BY, UPDATED_BY)
VALUES
    (4, 'PRIORITIZED', 2, '#FFFF00', TRUE, 'system', 'system');

INSERT INTO FD_PROGRESS_STATUS 
    (COMPANY_ID, PROGRESS_NAME, PROGRESS_SEQUENCE, COLOR_CODE, IS_ACTIVE, CREATED_BY, UPDATED_BY)
VALUES
    (2, 'In Test', 5, '#F59E0B', TRUE, 'system', 'system');

INSERT INTO FD_PROGRESS_STATUS 
    (COMPANY_ID, PROGRESS_NAME, PROGRESS_SEQUENCE, COLOR_CODE, IS_ACTIVE, CREATED_BY, UPDATED_BY)
VALUES
    (2, 'Blocked', 6, '#F44336', TRUE, 'system', 'system');


-- Company 1 acts only as a Service Provider
INSERT INTO FD_COMPANY_ROLES (
    COMPANY_ID, MAPPING_ID, IS_SERVICE_PROVIDER, IS_REQUESTOR, IS_BOTH, IS_ACTIVE, CREATED_BY
) VALUES (
    3, 3, FALSE, FALSE, TRUE, TRUE, 'ADMIN'
);

-- Company 2 acts only as a Requestor
INSERT INTO FD_COMPANY_ROLES (
    COMPANY_ID, MAPPING_ID, IS_SERVICE_PROVIDER, IS_REQUESTOR, IS_BOTH, IS_ACTIVE, CREATED_BY
) VALUES (
    3, 2, TRUE, FALSE, FALSE, TRUE, 'ADMIN'
);

-- Company 3 acts as Both (Service Provider + Requestor)
INSERT INTO FD_COMPANY_ROLES (
    COMPANY_ID, MAPPING_ID, IS_SERVICE_PROVIDER, IS_REQUESTOR, IS_BOTH, IS_ACTIVE, CREATED_BY
) VALUES (
    3, 4, TRUE, FALSE, FALSE, TRUE, 'ADMIN'
);
