DROP TABLE FD_REQUEST_ITEM;
DROP TABLE FD_INCIDENT;
DROP TABLE FD_TICKET_WATCHLIST;
DROP TABLE FD_TICKET;
DROP SEQUENCE IF EXISTS REQUEST_ITEM_SEQ CASCADE;
DROP SEQUENCE IF EXISTS INCIDENT_SEQ CASCADE;
DROP SEQUENCE IF EXISTS TICKET_WATCHLIST_SEQ CASCADE;
DROP SEQUENCE IF EXISTS TICKET_SEQ CASCADE;