ALTER TABLE FD_REQUEST_CONFIG
    ADD COLUMN CALL_HORIZON_PERCENTAGE INT DEFAULT 0;

ALTER TABLE FD_REQUEST_CONFIG
    ADD COLUMN CALL_HORIZON_DAYS INT DEFAULT 0;

ALTER TABLE FD_REQUEST_CONFIG
    ADD COLUMN IS_ENABLED BOOLEAN DEFAULT FALSE;

ALTER TABLE FD_REQUEST_CONFIG
    ADD COLUMN CURRENT_RANGE INT DEFAULT 0;