-- Alter FD_SYSTEM_AUDIT table to remove unnecessary columns
ALTER TABLE FD_SYSTEM_AUDIT
DROP COLUMN USER_NAME,
DROP COLUMN REQUEST_ID,
DROP COLUMN SESSION_ID,
DROP COLUMN DESCRIPTION,
DROP COLUMN URL,
DROP COLUMN HTTP_METHOD,
DROP COLUMN IP_ADDRESS,
DROP COLUMN USER_AGENT;