INSERT INTO FD_COUNTRY_MASTER (COUNTRY_NAME, ISO_CODE, CREATED_BY)
VALUES
('Afghanistan', 'AF', 'system'),
('Albania', 'AL', 'system'),
('Algeria', 'DZ', 'system'),
('Andorra', 'AD', 'system'),
('American Samoa', 'AS', 'system'),
('Angola', 'AO', 'system'),
('Argentina', 'AR', 'system'),
('Australia', 'AU', 'system'),
('Austria', 'AT', 'system'),
('Bangladesh', 'BD', 'system'),
('Belgium', 'BE', 'system'),
('Brazil', 'BR', 'system'),
('Canada', 'CA', 'system'),
('China', 'CN', 'system'),
('France', 'FR', 'system'),
('Germany', 'DE', 'system'),
('India', 'IN', 'system'),
('Italy', 'IT', 'system'),
('Japan', 'JP', 'system'),
('Mexico', 'MX', 'system'),
('Netherlands', 'NL', 'system'),
('Russia', 'RU', 'system'),
('South Africa', 'ZA', 'system'),
('United Kingdom', 'GB', 'system'),
('United States', 'US', 'system');
